using System.Collections.Generic;
using UnityEngine;

namespace Project.Character.Hair
{
    /// <summary>
    /// List of the selectable hairstyles. The position of an entry is its style index. The list
    /// is generated by the Rebuild Hair Catalog menu item from the models in the Hair folder.
    /// </summary>
    [CreateAssetMenu(menuName = "Character/Hair Catalog", fileName = "HairCatalog")]
    public sealed class HairCatalog : ScriptableObject
    {
        [SerializeField] private List<HairStyleEntry> styles = new List<HairStyleEntry>();

        /// <summary>
        /// The selectable hairstyles in index order.
        /// </summary>
        public IReadOnlyList<HairStyleEntry> Styles => styles;

        /// <summary>
        /// Replaces the stored hairstyles. Used by the catalog builder.
        /// </summary>
        /// <param name="entries">Hairstyles in index order.</param>
        public void SetStyles(IEnumerable<HairStyleEntry> entries)
        {
            styles = new List<HairStyleEntry>(entries);
        }

        /// <summary>
        /// Finds the position of a hairstyle by its stable identifier.
        /// </summary>
        /// <param name="id">The identifier, see <see cref="HairStyleEntry.Id"/>.</param>
        /// <returns>The index of the hairstyle, or -1 when it is not in the catalog.</returns>
        public int IndexOfId(string id)
        {
            for (int i = 0; i < styles.Count; i++)
            {
                if (styles[i].Id == id)
                {
                    return i;
                }
            }

            return -1;
        }

        /// <summary>
        /// Looks up a hairstyle by index.
        /// </summary>
        /// <param name="index">Style index.</param>
        /// <param name="entry">The hairstyle when the index is valid.</param>
        /// <returns>True when the index points at a hairstyle with a model.</returns>
        public bool TryGet(int index, out HairStyleEntry entry)
        {
            entry = index >= 0 && index < styles.Count ? styles[index] : null;
            return entry != null && entry.Prefab != null;
        }
    }
}
