using System.Collections.Generic;
using UnityEngine;

namespace Project.Character.Animation
{
    /// <summary>
    /// Names of the selectable eye and mouth drawings, in the same order as the layers of the
    /// face texture arrays. The list is generated by the Rebuild Face Textures menu item
    /// from the file names in the Eyes and Mouths folders.
    /// </summary>
    [CreateAssetMenu(menuName = "Character/Face Part Catalog", fileName = "FacePartCatalog")]
    public sealed class FacePartCatalog : ScriptableObject
    {
        [SerializeField] private List<string> eyeNames = new List<string>();
        [SerializeField] private List<string> mouthNames = new List<string>();

        /// <summary>
        /// Names of the eye drawings. The position of a name is its layer index.
        /// </summary>
        public IReadOnlyList<string> EyeNames => eyeNames;

        /// <summary>
        /// Names of the mouth drawings. The position of a name is its layer index.
        /// </summary>
        public IReadOnlyList<string> MouthNames => mouthNames;

        /// <summary>
        /// Replaces the stored names. Used by the texture builder.
        /// </summary>
        /// <param name="eyes">Eye drawing names in layer order.</param>
        /// <param name="mouths">Mouth drawing names in layer order.</param>
        public void SetNames(IEnumerable<string> eyes, IEnumerable<string> mouths)
        {
            eyeNames = new List<string>(eyes);
            mouthNames = new List<string>(mouths);
        }
    }
}
