using System.Collections.Generic;
using UnityEngine;

namespace Project.Character.Head
{
    /// <summary>
    /// List of the selectable head shapes. The first entry keeps the head of the body. The list is
    /// generated by the Rebuild Head Catalog menu item from the models in the Heads folders.
    /// </summary>
    [CreateAssetMenu(menuName = "Character/Head Catalog", fileName = "HeadCatalog")]
    public sealed class HeadCatalog : ScriptableObject
    {
        [SerializeField] private List<HeadStyleEntry> styles = new List<HeadStyleEntry>();

        /// <summary>
        /// The selectable head shapes in index order.
        /// </summary>
        public IReadOnlyList<HeadStyleEntry> Styles => styles;

        /// <summary>
        /// Replaces the stored head shapes. Used by the catalog builder.
        /// </summary>
        /// <param name="entries">Head shapes in index order.</param>
        public void SetStyles(IEnumerable<HeadStyleEntry> entries)
        {
            styles = new List<HeadStyleEntry>(entries);
        }

        /// <summary>
        /// Looks up the model of a head shape.
        /// </summary>
        /// <param name="index">Index of the head shape.</param>
        /// <param name="female">True for the female body, false for the male body.</param>
        /// <param name="model">The model when the entry has one for that body.</param>
        /// <returns>True when a model was found. False means the head of the body is used.</returns>
        public bool TryGetModel(int index, bool female, out GameObject model)
        {
            model = index >= 0 && index < styles.Count ? styles[index].GetModel(female) : null;
            return model != null;
        }
    }
}
